# Site settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Inquisitive Semantics" # the name of your site, e.g. ACME Corp.

# Build settings
sass:
  sass_dir: assets/css

# Collections
collections:
  courses:
    output: true
  workshops:
    output: true
theme: jekyll-theme-minimal