# Site settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/inquisitive-semantics" # the subpath of your site, e.g. /blog
title: "Inquisitive Semantics" # the name of your site, e.g. ACME Corp.
description: >
  Inquisitive semantics is a semantic framework that is 
  based on a formal notion of meaning which, unlike the 
  traditional truth-conditional notion, captures both 
  informative and inquisitive content.
credits: >
  This website is maintained by Floris Roelofsen. Webdesign and development by Bas Cornelissen and Marianne de Heer Kloots.

# Build settings
sass:
  sass_dir: assets/css

# Collections
collections:
  courses:
    output: true
  workshops:
    output: true
  pages:
    output: true
    permalink: /:name